# Generated by Django 4.2.13 on 2026-04-27 04:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('HOLD', 'Hold'), ('RELEASE', 'Release')], max_length=10)),
                ('amount_paise', models.BigIntegerField()),
                ('reference_type', models.CharField(blank=True, choices=[('PAYOUT', 'Payout'), ('CREDIT', 'Credit')], max_length=10, null=True)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
            ],
            options={
                'db_table': 'ledger_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'type'], name='ledger_entr_merchan_019835_idx'), models.Index(fields=['merchant', 'created_at'], name='ledger_entr_merchan_620720_idx')],
            },
        ),
    ]
